-- Final Support interactions upgrade.
-- Run once in Supabase SQL Editor AFTER deploying the matching code files.
-- Adds read receipts and one reaction per user/message without changing old messages.

begin;

do $$
begin
  if to_regclass('public.support_messages') is null then
    raise exception 'public.support_messages must exist before this upgrade';
  end if;
end $$;

create table if not exists public.support_message_reactions (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.support_messages(id) on delete cascade,
  user_id text not null,
  reaction text not null check (reaction in ('like','love','laugh','angry','sad','dislike')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists support_message_reactions_message_user_uidx
  on public.support_message_reactions(message_id, user_id);

create index if not exists support_message_reactions_message_idx
  on public.support_message_reactions(message_id);

create table if not exists public.support_message_reads (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.support_messages(id) on delete cascade,
  user_id text not null,
  read_at timestamptz not null default now()
);

create unique index if not exists support_message_reads_message_user_uidx
  on public.support_message_reads(message_id, user_id);

create index if not exists support_message_reads_message_idx
  on public.support_message_reads(message_id);

alter table public.support_message_reactions enable row level security;
alter table public.support_message_reads enable row level security;

-- Interaction data is available only through authenticated server routes.
revoke all on table public.support_message_reactions from anon, authenticated;
revoke all on table public.support_message_reads from anon, authenticated;
revoke all on sequence public.support_message_reactions_id_seq from anon, authenticated;
revoke all on sequence public.support_message_reads_id_seq from anon, authenticated;

commit;
